name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        build_type: [Release]

    steps:
    - uses: actions/checkout@v3

    - name: Run vcpkg
      uses: lukka/run-vcpkg@v11.1
      with:
        vcpkgGitCommitId: f6a5d4e8eb7476b8d7fc12a56dff300c1c986131

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_TOOLCHAIN_FILE:STRING=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake -DMEMORY_READER_BUILD_EXAMPLE=ON -DMEMORY_READER_BUILD_TESTING=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{matrix.build_type}}
